version: '3.7'

services:
  flask_api:
    build: ./app
    volumes:
      - ./app
    restart: always 
    ports:
      - 8080:8080

  # website:
  #   image: php:apache
  #   volumes:
  #     - ./website:/var/www/html
  #   ports:
  #     - 5000:80
  #   depends_on:
  #     - product-service